---
# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
docker_package: "docker-ce"

# Docker Compose options.
docker_compose_version: "1.26.0"
docker_compose_path: /usr/local/bin/docker-compose

# Used only for RedHat/CentOS/Fedora.
docker_yum_repo_url: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-ce.repo
docker_yum_repo_enable_nightly: '0'
docker_yum_repo_enable_test: '0'
docker_yum_gpg_key: https://download.docker.com/linux/centos/gpg

# A list of users who will be added to the docker group.
docker_users: []
docker_log_driver: "gcplogs"
docker_storage_driver: "overlay2"